name: goreleaser

on:
  push:
    branches: [master, main, force_test, release-*]
    tags: ['*']
  pull_request:
    branches: ['**']

env:
  golang-version: 1.18.2

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.1.0
        with:
          go-version: ${{ env.golang-version }}
      
      - name: GoReleaser Test
        uses: goreleaser/goreleaser-action@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          distribution: goreleaser
          version: latest
          workdir: cli
          args: release --snapshot --skip-publish --rm-dist
      
      - name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        #release only on tags
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          workdir: cli
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
