name: goreleaser

on:
  push:
    tags: ['*']

env:
  helm-version: v3.9.0

jobs:
  publish-chart:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           fetch-depth: 0

       - name: Set up Helm
         uses: azure/setup-helm@v2.1
         with:
           version: ${{ env.helm-version }}

       - name: Create package
         env:
           AWS_REGION: 'us-east-1'
           AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_SECRET_ACCESS_KEY }}
         run: |
             mkdir -p chart_release
             helm dep up chart
             helm package chart -d chart_release/
             helm plugin install https://github.com/hypnoglow/helm-s3.git          
             helm repo add tscharts s3://charts.timescale.com
             helm s3 push chart_release/* tscharts --acl public-read --relative --dry-run
       - name: push package
         env:
           AWS_REGION: 'us-east-1'
           AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_SECRET_ACCESS_KEY }}
         run: |
           helm s3 push chart_release/* tscharts --acl public-read --relative
